export const UPDATE_NAME_FILTER = 'UPDATE_NAME_FILTER'
export const UPDATE_CLUB_FILTER = 'UPDATE_CLUB_FILTER'
export const UPDATE_POSITION_FILTER = 'UPDATE_POSITION_FILTER'
export const UPDATE_PRICE_FILTER = 'UPDATE_PRICE_FILTER'
export const UPDATE_RANK_FILTER = 'UPDATE_RANK_FILTER'
export const RESET_FILTERS = 'RESET_FILTERS'

export const INVALIDATE_DATA = 'INVALIDATE_DATA'
export const REQUEST_DATA = 'REQUEST_DATA'
export const RECEIVE_DATA = 'RECEIVE_DATA'

export const UPDATE_TEAM_NAME = 'UPDATE_TEAM_NAME'
export const SELECT_PLAYER = 'SELECT_PLAYER'
export const REMOVE_PLAYER = 'REMOVE_PLAYER'
