//Filters
export const UPDATE_NAME_FILTER = 'UPDATE_NAME_FILTER'
export const UPDATE_CLUB_FILTER = 'UPDATE_CLUB_FILTER'
export const UPDATE_POSITION_FILTER = 'UPDATE_POSITION_FILTER'
export const UPDATE_PRICE_FILTER = 'UPDATE_PRICE_FILTER'
export const UPDATE_RANK_FILTER = 'UPDATE_RANK_FILTER'
export const RESET_FILTERS = 'RESET_FILTERS'

//Data Call
export const INVALIDATE_DATA = 'INVALIDATE_DATA'
export const REQUEST_DATA = 'REQUEST_DATA'
export const RECEIVE_DATA = 'RECEIVE_DATA'

//Team Selection
export const UPDATE_TEAM_NAME = 'UPDATE_TEAM_NAME'
export const TOGGLE_PLAYER_SELECT = 'TOGGLE_PLAYER_SELECT'
